workspace:
  base: /workspace
  path: src/github.com/bitlogic/bitlogic.io
pipeline:
  optimize-content:
    image: alexac/alpine-grunt-bower
    script:
      - npm install
      - grunt 
  dockerize-site:
    image: plugins/docker
    repo: bitlogicos/bitlogic-io
    tag:
    - latest
    - "1.0.${DRONE_BUILD_NUMBER}"
  deploy-to-8080:
      image: plugins/ssh
      host: i1.bitlogic.io
      user: ec2-user
      port: 22
      script:
        - docker pull bitlogicos/bitlogic-io
        - docker rm -f beta || true
        - docker run --name beta -p 8080:80 -d bitlogicos/bitlogic-io
  run-smoke-test:
      image: bitlogicos/bitlogic-io-test
      pull: true
      

        