workspace:
  base: /workspace
  path: src/github.com/bitlogic/bitlogic.io
pipeline:
  build-content:
    image: alexac/alpine-grunt-bower
    commands:
      - npm install
      - grunt 
  dockerize-site:
    image: plugins/docker
    repo: bitlogicos/bitlogic-io
    tag:
    - latest
    - "1.0.${DRONE_BUILD_NUMBER}"
  deploy:
      image: plugins/ssh
      host: www.bitlogic.io
      user: ubuntu
      port: 22
      script:
        - docker pull bitlogicos/bitlogic-io
        - docker rm -f site || true
        - docker run --name site -p 80:80 -d bitlogicos/bitlogic-io:local
  run-smoke-test:
      image: bitlogicos/bitlogic-io-test
      pull: true
